language: node_js
node_js:
  - 8
  - 10
cache:
  yarn: true
before_install:
  - yarn add -g codecov
scripts:
  - yarn test --ci
after_success:
  - codecov
  - yarn add -g typescript
deploy:
  provider: npm
  email: capajj@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: false
